server:
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never

logging.level:
  org.hibernate.SQL: trace


spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: dgCCTwG3qUzHml2wciNo
            client-secret: r0TKELK5BX
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            client-authentication-method: client_secret_get
            authorization-grant-type: authorization_code
            scope: # naver 개인 정보 동의 항목 설정의 ID 값
              - profile_nickname
              - profile_image
              - account_email
            client-name: naver

        # naver provider 설정
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: id # 유저 정보 조회 시 반환되는 최상위 필드명으로 해야 한다.

jwt:
  secret-key: 'fa5e2d1c7e68b4173f7099a756a243d2b84e3a3d1c4b6f0ed9e4bebf4682d22f'
  refresh-token-expiration-millis: 31536000000 #86400000
  access-token-expiration-millis: 86400000 #3600000

